<?php
if ( !defined('pokemon') ) exit(); //This can only be included after an initial call.



//STATUS EFFECTS
define('ST_NULL',0,true); /** Null Status */
define('ST_BURN',1,true); /** Burn Status */ //MAJOR
define('ST_FAINT',2,true); //MAJOR
define('ST_FREEZE',3,true); //MAJOR
define('ST_PARALYZE',4,true); //MAJOR
define('ST_POISON',5,true); //MAJOR
define('ST_SLEEP',6,true); //MAJOR
define('ST_TOXIC',7,true);
define('ST_CONFUSE',8,true);
define('ST_ATTRACT',9,true);
define('ST_FLINCH',10,true);
define('ST_TRAP',11,true);
define('ST_UNCONTROL',12,true);
define('ST_GHOSTCURSE',13,true);
define('ST_LEECHSEED',14,true);
define('ST_NIGHTMARE',15,true);
define('ST_PERISHCOUNT',16,true);
define('ST_TAUNT',17,true);
define('ST_TORMENT',18,true);
define('ST_DISABLE',19,true);

/** Next Move Types */
define('MV_NULL',0,true);
define('MV_MOVE1',1,true);
define('MV_MOVE2',2,true);
define('MV_MOVE3',3,true);
define('MV_MOVE4',4,true);
define('MV_RUN',5,true);
define('MV_ITEM',6,true);
define('MV_CATCH',7,true);
define('MV_SWITCH',8,true);
define('MV_AI',9,true);
define('MV_PREPARE',10,true);

/** ATTACK TYPES */
define('ATK_UNKNOWN',0,true);
define('ATK_NORMAL',1,true);
define('ATK_SPECIAL',2,true);
define('ATK_STATUS',3,true);

       
/** ELEMENT TYPES 
00	 0x00	 Normal
01	 0x01	 Fighting
02	 0x02	 Flying
03	 0x03	 Poison
04	 0x04	 Ground
05	 0x05	 Rock
07	 0x07	 Bug
08	 0x08	 Ghost
20	 0x14	 Fire
21	 0x15	 Water
22	 0x16	 Grass
23	 0x17	 Electric
24	 0x18	 Psychic
25	 0x19	 Ice
26	 0x1A	 Dragon
*/
define('ET_NULL', 0, true);
define('ET_NORMAL',1,true);
define('ET_FIGHTING',2,true);
define('ET_FLYING',3,true);
define('ET_POISON',4,true);
define('ET_GROUND',5,true);
define('ET_ROCK',6,true);
define('ET_BUG',7,true);
define('ET_GHOST',8,true);
define('ET_FIRE',9,true);
define('ET_WATER',10,true);
define('ET_GRASS',11,true);
define('ET_ELECTRIC',12,true);
define('ET_PSYCHIC',13,true);
define('ET_ICE',14,true);
define('ET_DRAGON',15,true);


/** GROWTH RATES */
define('G_SLOW',0, true);
define('G_MEDSLOW',1, true);
define('G_MEDFAST',2, true);
define('G_FAST',3, true);
define('G_OTHER',4, true);

/** ABILITY CONSTANTS */
define('SK_NULL',0,true);
define('SK_ABSORB',1,true);
define('SK_ACID',2,true);
define('SK_ACIDARMOR',3,true);
define('SK_AGILITY',4,true);
define('SK_AMNESIA',5,true);
define('SK_AURORABEAM',6,true);
define('SK_BARRAGE',7,true);
define('SK_BARRIER',8,true);
define('SK_BIDE',9,true);
define('SK_BIND',10,true);
define('SK_BITE',11,true);
define('SK_BLIZZARD',12,true);
define('SK_BODYSLAM',13,true);
define('SK_BONECLUB',14,true);
define('SK_BONEMERANG',15,true);
define('SK_BUBBLE',16,true);
define('SK_BUBBLEBEAM',17,true);
define('SK_CLAMP',18,true);
define('SK_COMETPUNCH',19,true);
define('SK_CONFUSERAY',20,true);
define('SK_CONFUSION',21,true);
define('SK_CONSTRICT',22,true);
define('SK_CONVERSION',23,true);
define('SK_COUNTER',24,true);
define('SK_CRABHAMMER',25,true);
define('SK_CUT',26,true);
define('SK_DEFENSECURL',27,true);
define('SK_DIG',28,true);
define('SK_DISABLE',29,true);
define('SK_DIZZYPUNCH',30,true);
define('SK_DOUBLEKICK',31,true);
define('SK_DOUBLETEAM',32,true);
define('SK_DOUBLEEDGE',33,true);
define('SK_DOUBLESLAP',34,true);
define('SK_DRAGONRAGE',35,true);
define('SK_DREAMEATER',36,true);
define('SK_DRILLPECK',37,true);
define('SK_EARTHQUAKE',38,true);
define('SK_EGGBOMB',39,true);
define('SK_EMBER',40,true);
define('SK_EXPLOSION',41,true);
define('SK_FIREBLAST',42,true);
define('SK_FIREPUNCH',43,true);
define('SK_FIRESPIN',44,true);
define('SK_FISSURE',45,true);
define('SK_FLAMETHROWER',46,true);
define('SK_FLASH',47,true);
define('SK_FLY',48,true);
define('SK_FOCUSENERGY',49,true);
define('SK_FURYATTACK',50,true);
define('SK_FURYSWIPES',51,true);
define('SK_GLARE',52,true);
define('SK_GROWL',53,true);
define('SK_GROWTH',54,true);
define('SK_GUILLOTINE',55,true);
define('SK_GUST',56,true);
define('SK_HARDEN',57,true);
define('SK_HAZE',58,true);
define('SK_HEADBUTT',59,true);
define('SK_HIJUMPKICK',60,true);
define('SK_HORNATTACK',61,true);
define('SK_HORNDRILL',62,true);
define('SK_HYDROPUMP',63,true);
define('SK_HYPERBEAM',64,true);
define('SK_HYPERFANG',65,true);
define('SK_HYPNOSIS',66,true);
define('SK_ICEBEAM',67,true);
define('SK_ICEPUNCH',68,true);
define('SK_JUMPKICK',69,true);
define('SK_KARATECHOP',70,true);
define('SK_KINESIS',71,true);
define('SK_LEECHLIFE',72,true);
define('SK_LEECHSEED',73,true);
define('SK_LEER',74,true);
define('SK_LICK',75,true);
define('SK_LIGHTSCREEN',76,true);
define('SK_LOVELYKISS',77,true);
define('SK_LOWKICK',78,true);
define('SK_MEDITATE',79,true);
define('SK_MEGADRAIN',80,true);
define('SK_MEGAKICK',81,true);
define('SK_MEGAPUNCH',82,true);
define('SK_METRONOME',83,true);
define('SK_MIMIC',84,true);
define('SK_MINIMIZE',85,true);
define('SK_MIRRORMOVE',86,true);
define('SK_MIST',87,true);
define('SK_NIGHTSHADE',88,true);
define('SK_PAYDAY',89,true);
define('SK_PECK',90,true);
define('SK_PETALDANCE',91,true);
define('SK_PINMISSILE',92,true);
define('SK_POISONGAS',93,true);
define('SK_POISONSTING',94,true);
define('SK_POISONPOWDER',95,true);
define('SK_POUND',96,true);
define('SK_PSYBEAM',97,true);
define('SK_PSYCHIC',98,true);
define('SK_PSYWAVE',99,true);
define('SK_QUICKATTACK',100,true);
define('SK_RAGE',101,true);
define('SK_RAZORLEAF',102,true);
define('SK_RAZORWIND',103,true);
define('SK_RECOVER',104,true);
define('SK_REFLECT',105,true);
define('SK_REST',106,true);
define('SK_ROAR',107,true);
define('SK_ROCKSLIDE',108,true);
define('SK_ROCKTHROW',109,true);
define('SK_ROLLINGKICK',110,true);
define('SK_SANDATTACK',111,true);
define('SK_SCRATCH',112,true);
define('SK_SCREECH',113,true);
define('SK_SEISMICTOSS',114,true);
define('SK_SELFDESTRUCT',115,true);
define('SK_SHARPEN',116,true);
define('SK_SING',117,true);
define('SK_SKULLBASH',118,true);
define('SK_SKYATTACK',119,true);
define('SK_SLAM',120,true);
define('SK_SLASH',121,true);
define('SK_SLEEPPOWDER',122,true);
define('SK_SLUDGE',123,true);
define('SK_SMOG',124,true);
define('SK_SMOKESCREEN',125,true);
define('SK_SOFTBOILED',126,true);
define('SK_SOLARBEAM',127,true);
define('SK_SONICBOOM',128,true);
define('SK_SPIKECANNON',129,true);
define('SK_SPLASH',130,true);
define('SK_SPORE',131,true);
define('SK_STOMP',132,true);
define('SK_STRENGTH',133,true);
define('SK_STRINGSHOT',134,true);
define('SK_STRUGGLE',135,true);
define('SK_STUNSPORE',136,true);
define('SK_SUBMISSION',137,true);
define('SK_SUBSTITUTE',138,true);
define('SK_SUPERFANG',139,true);
define('SK_SUPERSONIC',140,true);
define('SK_SURF',141,true);
define('SK_SWIFT',142,true);
define('SK_SWORDSDANCE',143,true);
define('SK_TACKLE',144,true);
define('SK_TAILWHIP',145,true);
define('SK_TAKEDOWN',146,true);
define('SK_TELEPORT',147,true);
define('SK_THRASH',148,true);
define('SK_THUNDER',149,true);
define('SK_THUNDERWAVE',150,true);
define('SK_THUNDERBOLT',151,true);
define('SK_THUNDERPUNCH',152,true);
define('SK_THUNDERSHOCK',153,true);
define('SK_TOXIC',154,true);
define('SK_TRANSFORM',155,true);
define('SK_TRIATTACK',156,true);
define('SK_TWINEEDLE',157,true);
define('SK_VICEGRIP',158,true);
define('SK_VINEWHIP',159,true);
define('SK_WATERGUN',160,true);
define('SK_WATERFALL',161,true);
define('SK_WHIRLWIND',162,true);
define('SK_WINGATTACK',163,true);
define('SK_WITHDRAW',164,true);
define('SK_WRAP',165,true);

/** MONSTERS **/
define('PK_NULL',0,true);
define('PK_ABRA',1,true);
define('PK_AERODACTYL',2,true);
define('PK_ALAKAZAM',3,true);
define('PK_ARBOK',4,true);
define('PK_ARCANINE',5,true);
define('PK_ARTICUNO',6,true);
define('PK_BEEDRILL',7,true);
define('PK_BELLSPROUT',8,true);
define('PK_BLASTOISE',9,true);
define('PK_BULBASAUR',10,true);
define('PK_BUTTERFREE',11,true);
define('PK_CATERPIE',12,true);
define('PK_CHANSEY',13,true);
define('PK_CHARIZARD',14,true);
define('PK_CHARMANDER',15,true);
define('PK_CHARMELEON',16,true);
define('PK_CLEFABLE',17,true);
define('PK_CLEFAIRY',18,true);
define('PK_CLOYSTER',19,true);
define('PK_CUBONE',20,true);
define('PK_DEWGONG',21,true);
define('PK_DIGLETT',22,true);
define('PK_DITTO',23,true);
define('PK_DODRIO',24,true);
define('PK_DODUO',25,true);
define('PK_DRAGONAIR',26,true);
define('PK_DRAGONITE',27,true);
define('PK_DRATINI',28,true);
define('PK_DROWZEE',29,true);
define('PK_DUGTRIO',30,true);
define('PK_EEVEE',31,true);
define('PK_EKANS',32,true);
define('PK_ELECTABUZZ',33,true);
define('PK_ELECTRODE',34,true);
define('PK_EXEGGCUTE',35,true);
define('PK_EXEGGUTOR',36,true);
define('PK_FARFETCHD',37,true);
define('PK_FEAROW',38,true);
define('PK_FLAREON',39,true);
define('PK_GASTLY',40,true);
define('PK_GENGAR',41,true);
define('PK_GEODUDE',42,true);
define('PK_GLOOM',43,true);
define('PK_GOLBAT',44,true);
define('PK_GOLDEEN',45,true);
define('PK_GOLDUCK',46,true);
define('PK_GOLEM',47,true);
define('PK_GRAVELER',48,true);
define('PK_GRIMER',49,true);
define('PK_GROWLITHE',50,true);
define('PK_GYARADOS',51,true);
define('PK_HAUNTER',52,true);
define('PK_HITMONCHAN',53,true);
define('PK_HITMONLEE',54,true);
define('PK_HORSEA',55,true);
define('PK_HYPNO',56,true);
define('PK_IVYSAUR',57,true);
define('PK_JIGGLYPUFF',58,true);
define('PK_JOLTEON',59,true);
define('PK_JYNX',60,true);
define('PK_KABUTO',61,true);
define('PK_KABUTOPS',62,true);
define('PK_KADABRA',63,true);
define('PK_KAKUNA',64,true);
define('PK_KANGASKHAN',65,true);
define('PK_KINGLER',66,true);
define('PK_KOFFING',67,true);
define('PK_KRABBY',68,true);
define('PK_LAPRAS',69,true);
define('PK_LICKITUNG',70,true);
define('PK_MACHAMP',71,true);
define('PK_MACHOKE',72,true);
define('PK_MACHOP',73,true);
define('PK_MAGIKARP',74,true);
define('PK_MAGMAR',75,true);
define('PK_MAGNEMITE',76,true);
define('PK_MAGNETON',77,true);
define('PK_MANKEY',78,true);
define('PK_MAROWAK',79,true);
define('PK_MEOWTH',80,true);
define('PK_METAPOD',81,true);
define('PK_MEW',82,true);
define('PK_MEWTWO',83,true);
define('PK_MOLTRES',84,true);
define('PK_MRMIME',85,true);
define('PK_MUK',86,true);
define('PK_NIDOKING',87,true);
define('PK_NIDOQUEEN',88,true);
define('PK_NIDORANF',89,true);
define('PK_NIDORANM',90,true);
define('PK_NIDORINA',91,true);
define('PK_NIDORINO',92,true);
define('PK_NINETALES',93,true);
define('PK_ODDISH',94,true);
define('PK_OMANYTE',95,true);
define('PK_OMASTAR',96,true);
define('PK_ONIX',97,true);
define('PK_PARAS',98,true);
define('PK_PARASECT',99,true);
define('PK_PERSIAN',100,true);
define('PK_PIDGEOT',101,true);
define('PK_PIDGEOTTO',102,true);
define('PK_PIDGEY',103,true);
define('PK_PIKACHU',104,true);
define('PK_PINSIR',105,true);
define('PK_POLIWAG',106,true);
define('PK_POLIWHIRL',107,true);
define('PK_POLIWRATH',108,true);
define('PK_PONYTA',109,true);
define('PK_PORYGON',110,true);
define('PK_PRIMEAPE',111,true);
define('PK_PSYDUCK',112,true);
define('PK_RAICHU',113,true);
define('PK_RAPIDASH',114,true);
define('PK_RATICATE',115,true);
define('PK_RATTATA',116,true);
define('PK_RHYDON',117,true);
define('PK_RHYHORN',118,true);
define('PK_SANDSHREW',119,true);
define('PK_SANDSLASH',120,true);
define('PK_SCYTHER',121,true);
define('PK_SEADRA',122,true);
define('PK_SEAKING',123,true);
define('PK_SEEL',124,true);
define('PK_SHELLDER',125,true);
define('PK_SLOWBRO',126,true);
define('PK_SLOWPOKE',127,true);
define('PK_SNORLAX',128,true);
define('PK_SPEAROW',129,true);
define('PK_SQUIRTLE',130,true);
define('PK_STARMIE',131,true);
define('PK_STARYU',132,true);
define('PK_TANGELA',133,true);
define('PK_TAUROS',134,true);
define('PK_TENTACOOL',135,true);
define('PK_TENTACRUEL',136,true);
define('PK_VAPOREON',137,true);
define('PK_VENOMOTH',138,true);
define('PK_VENONAT',139,true);
define('PK_VENUSAUR',140,true);
define('PK_VICTREEBEL',141,true);
define('PK_VILEPLUME',142,true);
define('PK_VOLTORB',143,true);
define('PK_VULPIX',144,true);
define('PK_WARTORTLE',145,true);
define('PK_WEEDLE',146,true);
define('PK_WEEPINBELL',147,true);
define('PK_WEEZING',148,true);
define('PK_WIGGLYTUFF',149,true);
define('PK_ZAPDOS',150,true);
define('PK_ZUBAT',151,true);

/** ITEMS */
define('IT_NULL',0, true);
define('IT_TM01',1, true);
define('IT_TM02',2, true);
define('IT_TM03',3, true);
define('IT_TM04',4, true);
define('IT_TM05',5, true);
define('IT_TM06',6, true);
define('IT_TM07',7, true);
define('IT_TM08',8, true);
define('IT_TM09',9, true);
define('IT_TM10',10, true);
define('IT_TM11',11, true);
define('IT_TM12',12, true);
define('IT_TM13',13, true);
define('IT_TM14',14, true);
define('IT_TM15',15, true);
define('IT_TM16',16, true);
define('IT_TM17',17, true);
define('IT_TM18',18, true);
define('IT_TM19',19, true);
define('IT_TM20',20, true);
define('IT_TM21',21, true);
define('IT_TM22',22, true);
define('IT_TM23',23, true);
define('IT_TM24',24, true);
define('IT_TM25',25, true);
define('IT_TM26',26, true);
define('IT_TM27',27, true);
define('IT_TM28',28, true);
define('IT_TM29',29, true);
define('IT_TM30',30, true);
define('IT_TM31',31, true);
define('IT_TM32',32, true);
define('IT_TM33',33, true);
define('IT_TM34',34, true);
define('IT_TM35',35, true);
define('IT_TM36',36, true);
define('IT_TM37',37, true);
define('IT_TM38',38, true);
define('IT_TM39',39, true);
define('IT_TM40',40, true);
define('IT_TM41',41, true);
define('IT_TM42',42, true);
define('IT_TM43',43, true);
define('IT_TM44',44, true);
define('IT_TM45',45, true);
define('IT_TM46',46, true);
define('IT_TM47',47, true);
define('IT_TM48',48, true);
define('IT_TM49',49, true);
define('IT_TM50',50, true);
define('IT_TM51',51, true);
define('IT_TM52',52, true);
define('IT_TM53',53, true);
define('IT_TM54',54, true);
define('IT_TM55',55, true);
define('IT_TM56',56, true);
define('IT_TM57',57, true);
define('IT_TM58',58, true);
define('IT_TM59',59, true);
define('IT_TM60',60, true);
define('IT_TM61',61, true);
define('IT_TM62',62, true);
define('IT_TM63',63, true);
define('IT_TM64',64, true);
define('IT_ANTIDOTE',65, true);
define('IT_AWAKENING',66, true);
define('IT_BICYCLE',67, true);
define('IT_BIKEVOUCHER',68, true);
define('IT_BURNHEAL',69, true);
define('IT_CALCIUM',70, true);
define('IT_CARDKEY',71, true);
define('IT_COINCASE',72, true);
define('IT_DIREHIT',73, true);
define('IT_DOMEFOSSIL',74, true);
define('IT_ELIXER',75, true);
define('IT_ESCAPEROPE',76, true);
define('IT_ETHER',77, true);
define('IT_EXPERIENCEALL',78, true);
define('IT_FIRESTONE',79, true);
define('IT_FRESHWATER',80, true);
define('IT_FULLHEAL',81, true);
define('IT_FULLRESTORE',82, true);
define('IT_GOLDTEETH',83, true);
define('IT_GOODROD',84, true);
define('IT_GREATBALL',85, true);
define('IT_GUARDSPECIAL',86, true);
define('IT_HELIXFOSSIL',87, true);
define('IT_HPUP',88, true);
define('IT_HYPERPOTION',89, true);
define('IT_ICEHEAL',90, true);
define('IT_IRON',91, true);
define('IT_ITEMFINDER',92, true);
define('IT_LEAFSTONE',93, true);
define('IT_LEMONADE',94, true);
define('IT_LIFTKEY',95, true);
define('IT_MASTERBALL',96, true);
define('IT_MAXELIXIR',97, true);
define('IT_MAXETHER',98, true);
define('IT_MAXPOTION',99, true);
define('IT_MAXREPEL',100, true);
define('IT_MAXREVIVE',101, true);
define('IT_MOONSTONE',102, true);
define('IT_NUGGET',103, true);
define('IT_OAKSPARCEL',104, true);
define('IT_OLDAMBER',105, true);
define('IT_OLDROD',106, true);
define('IT_PARALYZEHEAL',107, true);
define('IT_POKEBALL',108, true);
define('IT_POKEDOLL',109, true);
define('IT_POKEFLUTE',110, true);
define('IT_POTION',111, true);
define('IT_PPUP',112, true);
define('IT_PROTEIN',113, true);
define('IT_RARECANDY',114, true);
define('IT_REPEL',115, true);
define('IT_REVIVE',116, true);
define('IT_SSTICKET',117, true);
define('IT_SAFARIBALL',118, true);
define('IT_SECRETKEY',119, true);
define('IT_SILPHSCOPE',120, true);
define('IT_SODAPOP',121, true);
define('IT_SUPERPOTION',122, true);
define('IT_SUPERREPEL',123, true);
define('IT_SUPERROD',124, true);
define('IT_THUNDERSTONE',125, true);
define('IT_TOWNMAP',126, true);
define('IT_ULTRABALL',127, true);
define('IT_WATERSTONE',128, true);
define('IT_XACCURACY',129, true);
define('IT_XATTACK',130, true);
define('IT_XDEFEND',131, true);
define('IT_XSPECIAL',132, true);
define('IT_XSPEED',133, true);
define('IT_HM01',134, true);
define('IT_HM02',134, true);
define('IT_HM03',135, true);
define('IT_HM04',136, true);
define('IT_HM05',137, true);

